"use client";

import { useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Link from "next/link";
import { Home, ChevronRight, BookOpen, FileText, CheckCircle, Users, Calendar, CreditCard, ArrowRight } from "lucide-react";

export default function FDMPage() {
  const [activeTab, setActiveTab] = useState("overview");
  
  
const objectives = [
    "To provide a strong grasp of fashion evolution and cultural relevance of clothing to encourage design output generated by inspiration and research.",
    "To provide students with a thorough comprehension of the design process through critical creative thinking, computer aided design, along with conceptual and experimental exploration.",
    "To address specific areas of apparel manufacturing, marketing, management and research related to the fashion industry."
  ];
  
 
  const curriculum = {
    "Semester 1": [
      "Applied Sciences",
      "Fibre to Fabric",
      "Elements and Principles of Design",
      "Professional Communication",
      "Fashion Illustration Laboratory",
      "Art and Material Exploration Laboratory",
      "Surface Embellishment Laboratory",
      "Industrial Visit and Presentation I",
      "Personality and Character Development",
    ],
    "Semester 2": [
      "Fashion Business",
      "Creative Thinking",
      "Process Flow in Apparel Manufacturing",
      "Pattern Making and Garment Construction",
      "Fabric Structure and Design Laboratory",
      "Dyeing and Printing Laboratory",
      "Pattern Making and Garment Construction Laboratory ",
      "Colour and Fabric Rendering Laboratory",
      "Personality and Character Development",
    ],
    "Semester 3": [
      "Textile and Apparel Quality Evaluation",
      "Circular Design and Sustainability",
      "Trend Forecasting and Fashion Design Process",
      "Principles of Management",
      "Historic Costume Designing Laboratory",
      "Computer Aided Fashion Design Laboratory I",
      "Flat Pattern Designing and Construction Laboratory",
      "Industrial Visit and Lecture II",
    ],
    "Semester 4": [
      "Apparel Marketing",
      "Fashion Communication",
      "Indian Traditional Textiles and Craft",
      "Apparel Costing",
      "Fashion Photography Process Laboratory",
      "Computer Aided Fashion Design Laboratory II",
      "Apparel Production Laboratory I",
      "Communication Design Laboratory",
    ],
    "Semester 5": [
      "Knitwear Design and Manufacture",
      "Apparel Production Planning and Control",
      "Fashion Retail Management",
      "Professional Elective I",
      "Fashion Photography Laboratory",
      "Computer Aided Fashion Design Laboratory III",
      "Apparel Production Laboratory II",
      "Craft Training and Documentation",
    ],
    "Semester 6": [
      "Fashion Research Methods",
      "Apparel Buying and Merchandising",
      "Visual Merchandising and Store Planning",
      "Professional Elective II",
      "Digital Fashion Laboratory",
      "Apparel Production Laboratory III",
      "Fashion Draping Laboratory",
      "Industrial Visit and Presentation III",
    ],
    "Semester 7": [
      "Project Work I",
    ],
    "Semester 8": [
      "Ergonomics in Clothing Design",
      "Professional Elective III",
      "Professional Elective IV",
      "Open Elective I",
      "Computer Aided Apparel Design Laboratory",
      "Fashion Accessories Laboratory",
      "Fashion Innovation and Product Development",
    ],
    "Semester 9": [
      "Entrepreneurship",
      "Professional Elective V",
      "Professional Elective VI",
      "Open Elective II",
      "Design Development and Portfolio Presentation",
    ],
    "Semester 10": [
      "Project Work II",
    ],
  "Design Electives":
  [
    "Conceptual Design and Innovation",
    "Design Thinking",
    "Fashion Journalism",
    "Fashion Styling",
    "Haute Couture Design",
    "Theatre and Film Costumes",
  ],
  "Production Electives":[
    "Artificial Intelligence in Fashion Industry",
    "Clothing Comfort",
    "Ergonomics in Apparel Industry",
    "Finishing and Clothing Care",
    "Functional Apparels",
    "Lean tools in Apparel Manufacturing",
  ],
  "Management Electives":[
    "Brand Marketing and Management",
    "Digital Fashion Marketing and Promotion",
    "Fashion Consumer Behaviour",
    "Financial Management",
    "Global Marketing and Export Management",
    "Intellectual Property Rights",
    "Logistics and Supply Chain Management",
    "Strategic Business Management",
  ],
  "Open Electives":[
    "Body Language for Professionals",
    "Nutrition and Dietetics",
    "UI/UX Design",
    "Emotional Intelligence",
  ],
};
  const alumni = [
    {
      name: "Mithun Raaju T. SK",
      position: "Production leader industrialization and Quality, Decathlon Prodin Sporting Pvt. Ltd., Coimbatore",
      batch: "M.Sc FDM (2015-2020)",
      testimonial: "\"PSG College of Technology\"always proves to be the top-ranking college in providing knowledge as well as guiding students towards a positive living. I am so grateful to the wonderful faculty of Apparel and Fashion Design department who groomed me a lot in enhancing my skills and placing me in a better position. My education from PSG College of Technology has allowed me to begin a successful and fulfilling career at Decathlon Company. I owe huge respect, love and devotion to entire faculty members and department. It's their efforts that make me to count myself into better professional. I am thankful to Training & Placement cell for providing a platform to enhance my skills and an opportunity to showcase them. Thanks to the department for helping me to get placed for moving in to my successful career.",
      image: "/fd_alumni/mithun.png"
    },
    {
      name: "Aathirai S",
      position: "Proprietor of Aura Brand, KPN Colony, Tiruppur",
      batch: "M.Sc FDM (2015-2020)",
      testimonial: "Choosing M.Sc. Fashion Designing and Merchandising is one of the best decisions of my life. Though, initially I was skeptical about the course, since, we were the first batch and I wasn’t into designing, day by day, year by year, it proved me wrong because FDM is more than just a normal designing course. It is a carefully put together cusp of production, designing and management by experts. We have an amazing panel of faculties from whom we learn so much more than just the curriculum, including, time management, professionalism, leadership, inter-personal skills, all of which are crucial for both professional and personal growth. We have industrial visits, cluster visits, complete internship in two semesters (seventh and tenth to be precise) all of which mould us into professional individuals by honing the key skills required by the industries. Overall, it’s a blue-chip course designed to not only teach everything you need to know but lead you in the right direction to be able to succeed. Altogether the complete learning’s from the course made to strive as an successful entrepreneur now.",
      image: "/fd_alumni/aathirai.png"
      
    },
    {
      name: "Sabitha R",
      position: "Production Planner, M/s Oshadi Collective, Chithode, Erode",
      batch: "M.Sc FDM (2016-2021)",
      testimonial: "I was a person who did not have any idea about my career after schooling. I got my admission in M.Sc Fashion Design and Merchandising Programme at PSG Tech and that's the turning point that happened in my life. 5 years of my college life taught me to manage all my responsibilities and still make time for the things I enjoy. The courses taught me in M.Sc FDM helped me to grow into a more confident person. I have learned to trust my own judgment and to stand up for myself when necessary. The main reason behind this is the selfless faculty who put all their efforts in sowing the seeds of knowledge which became a tree with strong roots. I am incredibly grateful to be a part of the Department of Apparel and Fashion Design and PSG TECH family.",
      image: "/fd_alumni/sabitha.jpeg"
      
    },
    {
      name: "Abirami Ashok Kumar S",
      position: "Designer & Proprietor, The Bee label, Coimbatore",
      batch: "M.Sc FDM (2016-2021)",
      testimonial: "I have always believed that the environment is the key to success. When you are not surrounded by the right people your goal will be delayed by 50%, so that's how crucial PSG Tech is for me and my milestones. Vision turned into reality of becoming a fashion designer when I took up the 5 year integrated M.Sc. Fashion Design and Merchandising programme. Though it was a huge step towards building a strong career yet the fear of studying 5 years straight in a row kept me petrified. But it turned out to be the place where I understood myself and learnt some life lessons, enriched by the constant guidance that was provided with efficient training. The department of Apparel and Fashion Design has nourished me with great knowledge by the supporting faculties and immense fun with my energetic peers. This college and the department has provided us the platform to build our character by enhancing our leadership and negotiation skills through various forum activities and events. It has the best curriculum that involves not just theoretical lectures but a lot of experimental and explorative opportunities to make learning more interesting, as well as to connect with new personalities which definitely will help groom one's future. This sure has been the amazing 5 years in my life and I owe a lot to PSG College of Technology for who I am today.",
      image: "/fd_alumni/abirami.png"
      
    },
    {
      name: "Nivedha C",
      position: "Fashion Designer, PH Project, Coimbatore",
      batch: "M.Sc FDM (2016-2021)",
      testimonial: "I have always wanted to be the best and so I chose to learn from the best. But when I entered PSG Tech, I was shocked. Guess what, it had more than what I expected. It was a great experience for me studying here. You laugh, you cry, you learn and you win. That’s exactly what happens here. All the faculties have been so friendly and keen on bringing out the talents from the fellow students. The five years at PSG Tech helped me to realise my skills and nourish them. Especially I’ve created a good network with lots of personalities which are really important in one’s life.",
      image: "/fd_alumni/nivedha.png"
      
    },
    {
      name: "Ragamalya M",
      position: "Associate Fashion Designer, Sakthi Infra tex Private Limited, Erode",
      batch: "M.Sc FDM (2016-2021)",
      testimonial: "PSG College of Technology, an institution where studies are perfectly balanced with extracurricular activities helping us to reach heights of success in every field. Professors are all experts in their respective fields thus enables us to be technically sound in our area of interest. The curriculum was challenging and the completion of work had offered a valuable insight and hands on experience in real world. Thus by providing a cross functional platform, PSG college of technology is one of the superlative choice for college.",
      image: "/fd_alumni/ragamalya.png"
      
    },
    {
      name: "Kaviya Prabha V",
      position: "Associate Fashion Designer, Sakthi Infra tex Private Limited, Erode",
      batch: "M.Sc FDM (2016-2021)",
      testimonial: "PSG College of Technology, an institution where studies are perfectly balanced with extracurricular activities helping us to reach heights of success in every field. Professors are all experts in their respective fields thus enables us to be technically sound in our area of interest. The curriculum was challenging and the completion of work had offered a valuable insight and hands on experience in real world. Thus by providing a cross functional platform, PSG college of technology is one of the superlative choice for college.",
      image: "/fd_alumni/kaviya.png"
      
    },
    {
      name: "Akshaya A. S.",
      position: "Production Leader Quality, M/s Prodin Sporting Goods, Decathlon, Coimbatore",
      batch: "M.Sc FDM (2017-2022)",
      testimonial: "Studying at PSG College of Technology was a pivotal experience in my life. From the moment, I stepped onto the campus, I knew that I was in for a transformative experience. I was excited to meet new people, learn from knowledgeable professors, and explore all that the college had to offer. I was particularly impressed by the amount of hands-on experience that was available. In addition to lectures, we had the opportunity to participate in lab experiments and projects that gave us a deeper understanding of the courses. I had the chance of meeting people from diverse backgrounds and interests, which helped me broaden my perspectives. It was amazing to be surrounded by individuals who were just as passionate about learning as I was overall, my experience at PSG College of Technology was one that I will never forget. I am grateful for the opportunities I had to learn, grow, and connect with others. As I move forward in my career, I will always carry the lessons and memories that I had at PSG Tech.",
      image: "/fd_alumni/akshaya.png"
      
    },
    {
      name: "Natchathirra S",
      position: "Founder- NIRRA studio, Tiruppur",
      batch: "M.Sc FDM (2018 - 2023)",
      testimonial: "My experience at PSG College of Technology was instrumental in paving the way for me to launch my own brand. The education I received there wasn't just about textbooks and lectures—it was an immersive journey that prepared me for the real-world challenges of entrepreneurship. From day one, The AFD department fostered an environment of innovation and excellence. The curriculum wasn't just theoretical; it was practical and hands-on, giving me the skills and knowledge I needed to succeed in the competitive world of business. The faculty were more than just teachers; they were mentors who guided me every step of the way. Their expertise and real-world experience were invaluable as I navigated the complexities of starting my own brand. Moreover, the college provided a range of resources and opportunities for budding entrepreneurs. Whether it was through workshops, networking events, or access to cutting-edge facilities, institutions offered the support I needed to turn my ideas into reality. Perhaps most importantly, PSG instilled in me a sense of confidence and resilience. Through projects, internships, and industry collaborations, I learned to tackle challenges head-on and adapt to changing circumstances—a skill that has been crucial in my entrepreneurial journey. As I look back on my time at PSG College of Technology, I'm filled with gratitude for the role it played in shaping my entrepreneurial path. The education and support I received there have been invaluable assets as I continue to grow and expand my brand.",
      image: "/fd_alumni/Natchatirra.png"
      
    },
  ];

  return (
    <main className="bg-[#f4f7fb] min-h-screen">
      <Header />

      {/* Hero Section */}

      <section className="relative pt-32 pb-20 bg-gradient-to-br from-[#0f172a] via-[#1e3a8a] to-[#0ea5e9] overflow-hidden">
        <div className="absolute inset-0 bg-black/20 backdrop-blur-[2px]"></div>

        <div className="relative z-10 max-w-7xl mx-auto px-4 grid lg:grid-cols-2 gap-12 items-center">

          {/* Left Content */}
          <div>
            <h1 className="text-4xl md:text-5xl font-bold text-white mb-4 leading-tight">
              M.Sc <span className="text-4xl md:text-5xl font-bold text-white mb-4 leading-tight">Fashion Design & Merchandising{" "} <span className="text-[#7dd3fc]">Programmes</span></span>
              
            </h1>

            <p className="text-white/80 text-2xl mb-6">
              Department of Apparel and Fashion Design
            </p>

            {/* Breadcrumb */}
            <div className="flex items-center gap-2 text-white/70">
              <Link href="/" className="flex items-center gap-1 hover:text-white transition-colors">
                <Home className="w-4 h-4" />
                Home
              </Link>

              <ChevronRight className="w-4 h-4" />

              <span className="text-white">Programme Details</span>
            </div>
          </div>


        </div>
      </section>

      {/* Main Content */}
      <section className="py-16">
        <div className="max-w-7xl mx-auto px-4">
          <div className="grid lg:grid-cols-3 gap-8">
            {/* Main Content */}
            <div className="lg:col-span-2">
              <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl shadow-xl overflow-hidden">
                <div className="p-6 border-b">
                  <h2 className="text-4xl font-bold text-[#1e3a8a]">M.Sc Fashion Design & Merchandising</h2>
      
                </div>
                
                {/* Tabs */}
                <div className="flex flex-wrap gap-2 p-4 bg-[#f7faff] border-b border-[#dce8f5]">
                  {[
                    { id: "overview", label: "Overview", icon: BookOpen },
                    { id: "curriculum", label: "Curriculum", icon: FileText },
                    { id: "selection", label: "Selection Process", icon: CheckCircle },
                    { id: "alumni", label: "Alumni Speaks", icon: Users },
                  ].map((tab) => (
                    <button
                      key={tab.id}
                      onClick={() => setActiveTab(tab.id)}
                      className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-all ${
                        activeTab === tab.id
                          ? "bg-gradient-to-r from-[#1e3a8a] to-[#0ea5e9] text-white shadow-md"
                          : "bg-white text-[#395A7F] border border-[#a3cae9] hover:bg-[#e8f4ff]"
                      }`}
                    >
                      <tab.icon className="w-4 h-4" />
                      {tab.label}
                    </button>
                  ))}
                </div>

                {/* Tab Content */}
                <div className="p-6">
                  {activeTab === "overview" && (
                    <div className="space-y-6">
                      <div>
                        <h4 className="text-2xl font-bold text-[#1c3879] mb-3">About the Department</h4>
                       <div className="space-y-6">
  {/* Block 1: The Intro Paragraph (This part is now safe) */}
  {/* <p className="text-xl text-gray-900 leading-relaxed text-justify">
    The <strong>Department of Apparel and Fashion Design </strong>offers a five year 
    integrated M.Sc. Fashion Design & Merchandising Programme, a first of its kind 
    at the university level. Over the past 10 years, it has sustained to build a 
    resource of versatile graduates who can face the challenges of the dynamic 
    fashion industry by applying design concepts creatively and conscientiously. 
    The department offers many prospects to envisage creative thinking, design thinking, 
    problem solving and research, thereby building students competency in providing 
    design solutions. The main objective of the department is to enable a holistic 
    development of future professionals to contribute the steering growth of the fashion, 
    apparel production and retail industry. By offering a comprehensive vision, the 
    department plays an integral role in shaping the students to become socially 
    responsible citizens.
  </p> */}
  <div className="text-xl text-gray-900 leading-relaxed mb-4 text-justify">

  <div className="mt-5">
    The <strong>Department of Apparel and Fashion Design </strong>offers a five year 
    integrated M.Sc. Fashion Design & Merchandising Programme, a first of its kind 
    at the university level. Over the past 10 years, it has sustained to build a 
    resource of versatile graduates who can face the challenges of the dynamic 
    fashion industry by applying design concepts creatively and conscientiously. 
    The department offers many prospects to envisage creative thinking, design thinking, 
    problem solving and research, thereby building students competency in providing 
    design solutions. The main objective of the department is to enable a holistic 
    development of future professionals to contribute the steering growth of the fashion, 
    apparel production and retail industry. By offering a comprehensive vision, the 
    department plays an integral role in shaping the students to become socially 
    responsible citizens.
  </div>
</div>
  {/* Block 2: The Objectives (Moved OUTSIDE of the <p> tag) */}
  {/* <div className="mt-10">
    <div className="grid gap-4">
      {objectives.map((obj, index) => (
        <div key={index} className="flex items-start gap-4 p-4 rounded-lg hover:bg-gray-50 transition-colors">
          <CheckCircle className="w-6 h-6 text-[#1c3879] mt-1 flex-shrink-0" />
          
          <p className="text-gray-900">{obj}</p>
        </div>
      ))}
    </div>
  </div> */}
</div>
                      </div>

                      <div>
                        <h4 className="text-2xl font-bold text-[#1c3879] mb-3">About the Programme</h4>
                        <p className="text-xl text-gray-900 leading-relaxed mb-4 text-justify">
                          The <strong>M.Sc Fashion Design & Merchandising</strong> is a five year integrated degree programme with a three-pronged approach to fashion education - <strong>design, production and management</strong> as core areas. Focusing on specific industry requirements in fashion, apparel, niche segments and craft sectors the curriculum progresses along distinct paths gradually from the foundation to the final year of the programme. The curriculum paves way to develop a strong foundation in fashion design and merchandising by offering six professional electives to strengthen the students' skills in core area of their interest. Employment enhancement courses like craft training and documentation, industrial visits, guest lectures and 2 six months internships in the curriculum enable the students to possess a sound knowledge in the industrial practices. Craft training provides a unique opportunity to experience the artistic craft making practices first hand by working with native rural artisans in craft clusters. Students also gain valuable insight into the wide spectrum of Indian fashion through internships and industry-based projects at leading export houses, retail brands and designer house. Design collection and portfolio based on a self-developed brief provides a platform to exhibit the creative skills of students, improve knowledge and overcome practical challenges thus making them a complete professional. The curriculum is set with the following Programme.<br/> <br/><strong>Educational Objectives:</strong></p>
                        <div className="mt-10">
                          <div className="grid gap-4">
                            {objectives.map((obj, index) => (
                              <div
                                key={index}
                                className="flex items-start gap-4 p-4 rounded-lg hover:bg-gray-50 transition-colors"
                              >
                                <CheckCircle className="w-6 h-6 text-[#1c3879] mt-1 flex-shrink-0" />
                                <p className="text-gray-900 text-xl">{obj}</p>
                              </div>
                            ))}
                          </div>
                        </div>
                      </div> 
                      {/* Integrated Facilities Section */}
                      <div className="pt-8 border-t border-gray-100">
                        <h4 className="text-2xl font-bold text-[#1c3879] mb-4">Facilities</h4>
                        <p className="text-xl text-gray-900 leading-relaxed mb-6 text-justify">
                          To give hands-on experience with industry-standards, the laboratories are equipped with the latest machinery and software.
                        </p>
                        <div className="mb-8 flex justify-center">
                          <img 
                            src="/image/fdm-facilities.png" 
                            alt="Fashion Design Infrastructure" 
                            className="w-full max-w-2xl h-auto rounded-xl shadow-md border border-gray-100"
                          />
                        </div>
                        <p className="text-xl text-gray-900 leading-relaxed text-justify">
                          Apart from the laboratories, the department has a well-established library with latest e-books, e-journals, text books, magazines and journals in the area of fashion design, art, craft, photography, production, and management.
                        </p>
                      </div>
                  {/* Integrated Co-curricular Section */}
                      <div className="pt-8 border-t border-gray-100">
                        <h4 className="text-2xl text-lg font-bold text-[#1c3879] mb-6">Co-curricular & Extra Curricular Activities</h4>
                        <div className="space-y-6">
                          <div className="flex items-start gap-4">
                            <CheckCircle className="w-6 h-6 text-[#1c3879] mt-1 flex-shrink-0" />
                            <p className="text-xl text-gray-900 leading-relaxed text-justify">
                              Students take part in various intra/inter college competitions such as product design development, illustration, logo designing, draping, paper presentations, painting, quiz and debate. They also take part in events organized by retailers and export industries. Apart from the co-curricular activities, students are also encouraged to participate in extracurricular activities in various clubs in college, sports, NCC and NSS to enhance their personality and character development.
                            </p>
                          </div>
                          <div className="flex items-start gap-4">
                            <CheckCircle className="w-6 h-6 text-[#1c3879] mt-1 flex-shrink-0" />
                            <p className="text-xl text-gray-900 leading-relaxed text-justify">
                              <strong>Apparel & Fashion Design Association (AFDA)</strong> is a students' forum, a crew of selected office bearers plans the event for the academic year and organizes design and technical events like seminars, workshops, symposia, exhibitions and the entire student members of AFDA participates in the proceedings. Eminent speakers from industry and academia deliver lectures on current trends in the apparel and fashion industry and this facilitates students' interaction with experts to develop a professional network.
                            </p>
                          </div>
                        </div>
                      </div>           
                    </div>
                  )}

                  {activeTab === "curriculum" && (
                    <div className="space-y-8">
                      <div className="grid md:grid-cols-2 gap-4">
                        {Object.entries(curriculum).map(([semester, subjects]) => (
                          <div key={semester} className="bg-[#f0f6ff] border border-[#c3ddf5] rounded-2xl p-5 hover:-translate-y-1 hover:shadow-md transition-all duration-300">
                            <h4 className="text-2xl font-bold text-lg mb-4">{semester}</h4>
                            <ul className="space-y-2">
                              {subjects.map((subject, idx) => (
                                <li key={idx} className="text-[#334155] text-lg flex items-start gap-2">
                                  <span className="w-1.5 h-1.5 bg-[#0ea5e9] rounded-full mt-1.5 flex-shrink-0 text-justify"></span>
                                  {subject}
                                </li>
                              ))}
                            </ul>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {activeTab === "selection" && (
                    <div className="space-y-6">
                      <div className="bg-white p-6 border rounded-xl shadow-sm">
                        <div className="space-y-6">
                          <p className="text-gray-900 leading-relaxed text-xl text-justify">
                            A good academic record in Higher Secondary examination (any group) of the
                            (10+2) curriculum prescribed by the appropriate authority of the Government
                            of Tamil Nadu or any other exam recognised as equivalent. Only Indian Nationals
                            are eligible to apply.
                          </p>

                          <p className="text-xl text-gray-900 leading-relaxed text-justify">
                            Shortlisted candidates with good academic record in Higher Secondary
                            examination (based on HSC total marks) will be called for counselling cum
                            admission in college campus to identify the commitment of the applicant to
                            study at PSG College of Technology.
                          </p>

                          <p className="text-xl text-gray-900 leading-relaxed text-justify">
                            The schedule of the counselling will be intimated through the applicant's
                            registered email.
                          </p>

                          <p className="text-xl text-gray-900 leading-relaxed text-justify">
                            However, call for counselling does not confer any right of admission.
                          </p>
                        </div>
                      </div>
                    </div>
                  )}
                
                  {activeTab === "alumni" && (
                    <div className="space-y-6">
                      <div className="space-y-6">
                        {alumni.map((alum, idx) => (
                          <div key={idx} className="program-card">
                            <div className="flex items-start gap-4">
                              <div className="w-24 h-24 bg-[#1c3879] rounded-full flex items-center justify-center flex-shrink-0">
                                <img
                                  src={alum.image}
                                  alt={alum.name}
                                  className="w-full h-full object-cover rounded-full"
                                />
                              </div>
                              <div>
                                <h5 className="text-2xl font-bold text-[#1a1a2e]">{alum.name}</h5>
                                <p className="text-[#1c3879] text-base font-medium">{alum.position}</p>
                                <p className="text-[#e8505b] text-sm">{alum.batch}</p>
                                <p className="text-gray-900 text-lg mt-3 leading-relaxed text-justify">
                                  {alum.testimonial}
                                </p>
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>

                      
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Sidebar */}
            <div className="space-y-6">

              
              {/* Important Dates */}
              <div className="bg-gradient-to-br from-[#1e3a8a] to-[#0ea5e9] text-white rounded-3xl p-6 shadow-xl">
                <h4 className="text-2xl font-bold mb-6">Important Dates</h4>
                <ul className="space-y-4">
                  <li className="flex items-start gap-3">
                    <Calendar className="w-5 h-5 text-[#e8505b] flex-shrink-0 mt-0.5" />
                    <div>
                      <p className="text-white/70 text-xl">Last date for application submission</p>
                      <p className="text-white font-bold">19th May 2026</p>
                    </div>
                  </li>
                  
                  <li className="flex items-start gap-3">
                    <Calendar className="w-5 h-5 text-[#e8505b] flex-shrink-0 mt-0.5" />
                    <div>
                      <p className="text-white/70 text-xl">Notification of shortlisted candidates for Counselling cum Admission in the campus</p>
                      <p className="text-white font-bold">21st May 2026</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <Calendar className="w-5 h-5 text-[#e8505b] flex-shrink-0 mt-0.5" />
                    <div>
                      <p className="text-white/70 text-xl">Last date for fee payment</p>
                      <p className="text-white font-bold">23rd May  2026</p>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <CreditCard className="w-5 h-5 text-[#e8505b] flex-shrink-0 mt-0.5" />
                    <div>
                      <p className="text-white/70 text-xl">Cost of application</p>
                      <p className="text-white font-bold">750 INR</p>
                    </div>
                  </li>
                </ul>
                <Link href="/apply" className="btn-secondary w-full justify-center mt-6">
                  Apply Now
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>

              {/* How to Apply */}
              <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl shadow-xl p-6">
                <h4 className="text-xl font-bold text-[#1c3879] mb-4">How to apply?</h4>
                <p className="text-gray-900 text-lg leading-relaxed text-justify">
                  Application can be made only through online by entering all the particulars including marks along with online payment by Net banking/Credit card/Debit card/UPI. All dates are subject to change based on HSC examination results.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
